config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_scope :user do
    get 'profile', action: :show, controller: 'users'
    devise_for :users, controllers: {registrations: 'users/registrations',
                                     omniauth_callbacks: 'users/omniauth_callbacks'}
  end

  resources :users, only: %i[index show]

  resources :posts, only: %i[new create index destroy]

  resources :likes, only: %i[create destroy]

  resources :friend_requests, only: %i[create destroy]
  resources :friendships, only: %i[create destroy]

  resources :notifications, only: %i[index destroy]

  resources :comments, only: %i[create destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)

    if @comment.save
      flash[:notice] = 'Added comment.'
    else
      flash[:alert] = 'Unable to add comment.'
    end

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back_or_to root_path }
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back_or_to root_path, status: :see_other }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment" id="<%= dom_id(comment) %>">
  <div class="comment-avatar">
    <% if comment.user.avatar.attached? %>
      <%= image_tag comment.user.avatar.representation(resize_to_fill: [180, 180]).processed.url, loading: 'lazy' %>
    <% end %>
  </div>
  <p class="comment-name"><%= comment.user.email %></p>
  <p class="comment-content"><%= comment.content %></p>
  <% if current_user.id == comment.user_id %>
    <%= link_to 'Delete', comment_path(comment.id), data: {
    turbo_method: :delete,
    turbo_confirm: 'Are you sure you wan to delete your comment?' } %>
  <% end %>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend dom_id(@comment.post, 'comments'), @comment %>

<%= turbo_stream.replace dom_id(@comment.post, 'comment_form'), partial: 'post_comment_new', locals: { post: @comment.post } %>

<%= turbo_stream.update dom_id(@comment.post, 'comments_toggle') do %>
  <%= pluralize(@comment.post.comments.length, 'Comment') %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>