config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_scope :user do
    get 'profile', action: :show, controller: 'users'
    devise_for :users, controllers: {registrations: 'users/registrations',
                                     omniauth_callbacks: 'users/omniauth_callbacks'}
  end

  resources :users, only: %i[index show]

  resources :posts, only: %i[new create index destroy]

  resources :likes, only: %i[create destroy]

  resources :friend_requests, only: %i[create destroy]
  resources :friendships, only: %i[create destroy]

  resources :notifications, only: %i[index destroy]

  resources :comments, only: %i[create destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  require 'open-uri'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  has_many :friend_requests
  has_many :friendships
  has_many :friends,
           through: :friendships

  has_many :likes
  has_many :liked_posts,
           through: :likes,
           source: :post

  has_many :notifications

  has_many :posts

  has_many :comments
  has_many :commented_posts,
           through: :comments,
           source: :post

  has_one_attached :avatar

  validate :avatar_format, :avatar_size, if: -> { avatar.attached? }

  def profile_details
    {
      biography:,
      real_name:,
      country:,
      state:,
      city:
    }
  end

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.username = auth.info.nickname
      user.password = Devise.friendly_token[0, 20]
      user.avatar.attach(io: URI.parse(auth.info.image).open, filename: 'github-avatar')
    end
  end

  private

  def avatar_format
    unless avatar.blob.image?
      errors.add(:base, 'Attached file must be an image')
    end
  end

  def avatar_size
    if avatar.blob.byte_size > 5.megabytes
      errors.add(:base, 'Attached file size must be less than 5 megabytes')
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :github

  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |resource|
      UserMailer.with(user: @user).welcome_email.deliver_later if resource.persisted?
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: [:avatar, :username, :real_name, :biography, :country, :state, :city]
    )
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    friend_requests = current_user.friend_requests

    @users = User.all.with_attached_avatar
    @friend_requester_ids = friend_requests.pluck(:friend_id)
    @friend_ids = current_user.friend_ids
    @friend_request_recipient_ids = FriendRequest.all.where(friend_id: current_user.id).pluck(:user_id)
  end

  def show
    user_id = params[:id] ||= current_user.id
    @user = User.find(user_id)
    @user_details = @user.profile_details
    @posts = @user
      .posts
      .includes(
        :liking_users,
        :comments
      )
      .with_attached_image
      .order(created_at: :desc)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h2>All users</h2>

<div class="users-container">
  <% @users.each do |user| %>
    <% next if current_user.id == user.id %>

    <div class="user-listing">

      <div class="listing-avatar">
        <% if user.avatar.attached? %>
          <%= image_tag user.avatar.representation(resize_to_fill: [180, 180]).processed.url, loading: 'lazy' %>
        <% end %>
      </div>

      <p><%= user.email %></p>

      <% if @friend_requester_ids.include?(user.id) %>
        <% friend_request = FriendRequest.find_sole_by(user_id: current_user, friend_id: user) %>

        <%= button_to 'Accept Friend Request', friendships_path, params: { user: current_user, friend: user } %>
        <%= button_to 'Decline Friend Request', friend_request_path(friend_request), params: { user: current_user, friend: user }, method: :delete %>
      <% elsif @friend_ids.include?(user.id) %>
        <% friendship = Friendship.find_sole_by(user_id: current_user, friend_id: user) %>
        <%= button_to 'Unfriend', friendship_path(friendship), params: { user: current_user, friend: user }, method: :delete %>
      <% elsif @friend_request_recipient_ids.include?(user.id) %>
        <% friend_request = FriendRequest.find_sole_by(user_id: user, friend_id: current_user) %>

        <%= button_to 'Cancel Friend Request', friend_request_path(friend_request), params: { user: user, friend: current_user }, method: :delete %>
      <% else %>
        <%= button_to 'Send Friend Request', friend_requests_path, params: { user:, friend: current_user } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h2><%= @user.username.present? ? @user.username : @user.email %>'s profile</h2>

<div class="profile-heading">
  <div class="profile-avatar">
    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar.representation(resize_to_fill: [180, 180]).processed.url %>
    <% end %>
  </div>

  <% if @user == current_user %>
    <%= link_to 'Edit Profile', edit_user_registration_path %>
  <% end %>

  <p><%= @user.username.present? ? @user.username : @user.email %></p>
</div>

<div class="profile-details">
  <% @user_details.each do |column_name, info| %>
    <% if info.present? %>
      <p class="column-name"><%= column_name.to_s.humanize %>:</p> <p class="column-info"><%= info %></p>
    <% end %>
  <% end %>
</div>

<h2><%= @user.username.present? ? @user.username : @user.email %>'s posts</h2>
<%=  render partial: 'post', collection: @posts %>