config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_scope :user do
    get 'profile', action: :show, controller: 'users'
    devise_for :users, controllers: {registrations: 'users/registrations',
                                     omniauth_callbacks: 'users/omniauth_callbacks'}
  end

  resources :users, only: %i[index show]

  resources :posts, only: %i[new create index destroy]

  resources :likes, only: %i[create destroy]

  resources :friend_requests, only: %i[create destroy]
  resources :friendships, only: %i[create destroy]

  resources :notifications, only: %i[index destroy]

  resources :comments, only: %i[create destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% flash.each do |type, message| %>
  <p class="flash-message <%= type %>"><%= message %></p>
<% end %>

app/views/application/_nav_bar.html.erb
<nav>
  <% if user_signed_in? %>
    <div class="notifications-nav">
      <%= link_to 'Notifications', notifications_path %> <%= current_user.notifications.size %>
    </div>
    <div class="links-nav">
      <%= link_to 'HOME', posts_path %>
      <%= link_to 'USERS', users_path %>
      <%= link_to 'PROFILE', profile_path %>
      <%= link_to 'LOG OUT', destroy_user_session_path, 'data-turbo-method': :delete %>
    <% else %>
      <%= link_to 'LOG IN', new_user_session_path %>
      <%= link_to 'SIGN UP', new_user_registration_path %>
    <% end %>
    </div>
</nav>

app/views/application/_post.html.erb
<div class="post" data-controller="comment" id="<%= dom_id(post) %>">
  <%= render 'post_heading', post: %>

  <%= render 'post_body', post: %>

  <%= turbo_frame_tag dom_id(post, 'liked_by_info') do %>
    <%= render 'post_liked_by', post: %>
  <% end %>

  <%= render 'post_interaction_buttons', post: %>

  <%= render 'post_comments_section', post: %>
</div>

app/views/application/_post_body.html.erb
<p class="post-content"><%= post.content %></p>

<% if post.image.attached? %>
  <div class="post-image">
    <%= image_tag post.image.representation(resize_to_fit: [nil, 500]).processed.url, loading: 'lazy' %>
  </div>
<% end %>

app/views/application/_post_comment_new.html.erb
<%= form_with model: Comment.new, class: 'new-comment-form', data: { 'comment-target': 'newCommentForm' }, namespace: post.id, id: dom_id(post, 'comment_form') do |form| %>
  <%= hidden_field_tag 'comment[post_id]', post.id, id: "#{ post.id }_comment_post_id" %>
  <%= form.text_area :content %>
  <%= form.submit %>
<% end %>

app/views/application/_post_comments.html.erb
<div class="post-comments hidden" data-comment-target="comments" id="<%= dom_id(post, 'comments') %>">
  <%= render partial: 'comments/comment', collection: post.comments.order(created_at: :desc) %>
</div>

app/views/application/_post_comments_section.html.erb
<div class="comments-section">
  <%= render 'post_comment_new', post: %>

  <%= render 'post_comments', post: %>
</div>

app/views/application/_post_heading.html.erb
<div class="post-heading">
  <div class="post-avatar">
    <% if post.user.avatar.attached? %>
      <%= image_tag post.user.avatar.representation(resize_to_fill: [180, 180]).processed.url, loading: 'lazy' %>
    <% end %>
  </div>

  <p><%= post.user.username.present? ? post.user.username : post.user.email %></p>

  <% if current_user.id == post.user_id %>
    <%= link_to 'Delete this post', post_path(post.id), data: {
      turbo_method: :delete,
      turbo_confirm: 'Are you sure you want to delete this post?' } %>
  <% end %>
</div>

app/views/application/_post_interaction_buttons.html.erb
<div class="post-interaction-buttons">
  <div class="post-like-unlike-form">
    <%= turbo_frame_tag dom_id(post, 'like_unlike_button') do %>
      <%= render 'post_like_unlike_button', post: %>
    <% end %>
  </div>

  <button type="button" class="comments-toggle"  data-action="click->comment#toggleVisibility" id="<%= dom_id(post, 'comments_toggle') %>">
    <%= pluralize(post.comments.length, 'Comment') %>
  </button>
</div>

app/views/application/_post_like_unlike_button.html.erb
<% if post.liking_users.include?(current_user) %>
  <% like = Like.find_by(post:, user: current_user) %>
  <%= button_to 'Unlike', like_path(like), method: :delete, class: 'post-unlike-button' %>
<% else %>
  <%= button_to 'Like', likes_path, params: { post:, user: current_user }, class: 'post-like-button'%>
<% end %>

app/views/application/_post_liked_by.html.erb
<p class="post-liked-by">
<% if post.liking_users.length > 0 %>
  Liked by
  <% post.liking_users.each do |user| %>
    <%= user.username.present? ? user.username : user.email %>
  <% end %>
<% else %>
  Be the first to like this post!
<% end %>
</p>